### ISSUE TITLE
Date Picker: Provide an option to disable user scroll

### ISSUE THREAD

**Issue by StefanOltmann** [alexzhirkevich/compose-cupertino#17]
The `HorizontalPager` has an issue with scrolling using the MacBooks touchpad. It works fine on Android & iOS.

That's why I usually disable this option until they get it fixed.

Please expose a parameter to disable it, so that Desktop users must use the dedicated buttons and will not get into the broken situation.

Maybe the components default should be `false` for Desktop apps, too.

https://github.com/alexzhirkevich/compose-cupertino/assets/9299303/b4b1cc8c-fc6d-4c9c-83ca-05eb8c6603ee

**Comment by alexzhirkevich** [comment]
Available in `0.1.0-alpha03`

**Comment by StefanOltmann** [comment]
Great! This problem is gone. :)

Changing the months of a date picker using the scrollbar is not a common practice anyway.
