### ISSUE TITLE
SystemBarStyle: Content color IOS 16.7 is always white

### ISSUE THREAD

**Issue by Lavmee** [alexzhirkevich/compose-cupertino#18]
On my test device (IPhone 8+, IOS 16.7) in the sample the content color of the StatusBar is always white.
I think you should try using the following code:

```kotlin
UIApplication.sharedApplication.setStatusBarStyle(
        if (isDark) UIStatusBarStyleLightContent else UIStatusBarStyleDarkContent
    )
viewController.setNeedsStatusBarAppearanceUpdate()
```

Screenshot of the problem:
![image](https://github.com/alexzhirkevich/compose-cupertino/assets/66745577/819d50a5-765e-4f6c-980f-8b9b60d5787f)

**Comment by alexzhirkevich** [comment]
It works well starting from iOS 17. I don't have simulator/device on iOS 16. Could you please apply this changes, test it and submit a PR? It should be applied inside `CupertinoTheme` function i guess. 
As i remember, you also need to add an additional property to `Info.plist` to change status bar color programmatically

**Comment by alexzhirkevich** [comment]
It also affects navigation bar strip at the bottom on iphones without home button i guess.
