### ISSUE TITLE
Min API 24

### ISSUE THREAD

**Issue by jacobras** [alexzhirkevich/compose-cupertino#22]
Is there a reason the [cupertino] / [cupertino-adaptive] library is published with min API 24 instead of say.. 21?

> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [io.github.alexzhirkevich:cupertino-android:0.1.0-alpha03] C:\Users\Jacob\.gradle\caches\transforms-3\9c3b934638cec0f83992d0e10deefac1\transformed\cupertino-release\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="io.github.alexzhirkevich.cupertino" to force usage (may lead to runtime failures)

If I suppress this error by using then the app runs fine on API 21.

```xml
tools:overrideLibrary="io.github.alexzhirkevich.cupertinonative,io.github.alexzhirkevich.cupertinoadaptive,io.github.alexzhirkevich.cupertinocore"
```

If the API 24 things are used in just a small part it would be great if they'd be guarded behind `Build.VERSION.SDK_INT` checks instead of a min SDK setting 😬

**Comment by alexzhirkevich** [comment]
Fixed in `0.1.0-alpha04`
