### ISSUE TITLE
NavigationBarItemColors values are unspecified.

### ISSUE THREAD

**Issue by begali** [alexzhirkevich/compose-cupertino#28]
NavigationBarItemColors values are unspecified when using compose-plugin version 1.6.0-rc03 or 1.6.0-rc02 on android. But when using compose-plugin version 1.5.12 working fine. Problem is occuring only on android. View hierarchy is as follow. AppTheme->Surface->AdaptiveScaffold->AdaptiveNavigationBar->AdaptiveNavigationBarItem. When inspecting via LayoutInspector.
![Image 27-2-24 at 11 57](https://github.com/alexzhirkevich/compose-cupertino/assets/6246247/4c8f443a-1a87-4a88-b5f4-46f30c953c46)

**Comment by alexzhirkevich** [comment]
Probably some backwards compatibility with JC failed. For now you can set these colors manually in the `adaptation` block

**Comment by begali** [comment]
Setting the colors in the adaption block worked. 
`adaptation = { material { colors = NavigationBarItemDefaults.colors() } }`

**Comment by alexzhirkevich** [comment]
Should be fixed in `0.1.0-alpha04`
