### ISSUE TITLE
No indication effect 

### ISSUE THREAD

**Issue by farr311** [alexzhirkevich/compose-cupertino#32]
Is it possible to not provide any **Indication** effect to components selectively? With material's **ripple effect** I'm able to do so through the use of a custom `NoRippleEffect` like this 
```Kotlin
private object NoRippleTheme : RippleTheme {
    @Composable
    override fun defaultColor() = Color.Unspecified

    @Composable
    override fun rippleAlpha(): RippleAlpha = RippleAlpha(0.0f,0.0f,0.0f,0.0f)
}
```
And then 
```Kotlin
CompositionLocalProvider(LocalRippleTheme provides NoRippleTheme) {
    content()
}
```

Is it possible to achieve something similar with the **Cupertino Indication**? 
I tried doing it this way
```Kotlin
internal class NoIndication: Indication {
    @Composable
    override fun rememberUpdatedInstance(interactionSource: InteractionSource): IndicationInstance {
        return remember {
            object : IndicationInstance {
                override fun ContentDrawScope.drawIndication() {
                    drawRect(
                        color = Color.Unspecified
                    )

                    drawContent()
                }
            }
        }
    }
}
```
But it didn't work for me unfortunately

**Comment by alexzhirkevich** [comment]
Which components you want to disable indication for?

**Comment by farr311** [comment]
Both buttons and column/row components. If at least the latter could work, that'd be immense

**Comment by alexzhirkevich** [comment]
For `Modifier.clickable` you can use overload with `indication` parameter or provide empty indication with `LocalIndication`

**Comment by farr311** [comment]
Thank you! That worked indeed

**Comment by alexzhirkevich** [comment]
Also for buttons there is a `indicationColor` parameter in the `ButtonColors` that you can set to transparent
