### ISSUE TITLE
Add support for sticky section titles in LazyListSection

### ISSUE THREAD

**Issue by farr311** [alexzhirkevich/compose-cupertino#34]
I'm experimenting with the section API at the moment, both the regular one and the lazy scope extension. Since sections typically have cleared defined "header" which in this instance is represented by the `title` composable, it would be nice to add a parameter `stickyTitle: Boolean = false` and then based on its value select between `item` and `stickyHeader`. Also it would be great to add some sort of a sticky state listener, so that code could be executed depending on whether the title is sticky at the moment or not (my use case for example, is to change the padding If the title becomes sticky)

This could be a nice addition to the seemingly upcoming section refactoring

**Comment by farr311** [comment]
I could definitely help out, as I've done something similar myself, but 1. I barely understand how compose works. 2. I've no idea what the guidelines for PR submissions would be

**Comment by alexzhirkevich** [comment]
Added `stickySection` in `0.1.0-alpha04`
