### ISSUE TITLE
AdaptiveScaffold background inconsistency

### ISSUE THREAD

**Issue by overpas** [alexzhirkevich/compose-cupertino#36]
[Reproducer](https://github.com/overpas/sample-cupertino-adaptive-bug)

The background color is set to `Color.Red` in Material scheme and systemBackground to `Color.Green` in Cupertino scheme. 
### Expected
background is red on android and green on iOS
### Actual
![ios](https://github.com/alexzhirkevich/compose-cupertino/assets/31508068/965d666d-5d46-481f-971a-63919e1811ad)
![android](https://github.com/alexzhirkevich/compose-cupertino/assets/31508068/8fcf3b8b-4aa4-44f3-b15d-ff85d08b431f)

**Comment by alexzhirkevich** [comment]
Fixed in `0.1.0-alpha04`
