### ISSUE TITLE
is the cupertino-decompose library only useful if client kmp project uses decompose?

### ISSUE THREAD

**Issue by BitByAVampire** [alexzhirkevich/compose-cupertino#43]
We are looking for ways to have ios native feel transitions between screens. We currently use Voyager for navigation. (not sure if you are familiar with that). would the cupertino-decompose library help in any way?

**Comment by alexzhirkevich** [comment]
Library itself won't be useful for voyager. You can check the source code for some references and try to reuse some parts with voyager

**Comment by BitByAVampire** [comment]
are there any sample code showing how the library is used? this would help me get an idea of how it can be worked into other projects. specifically how does the library hook to the existing navigation system used in an app to result in the transition effects?

**Comment by alexzhirkevich** [comment]
The `example` folder contains the app featured in preview movie, it contins navigation usage. If you are looking for integration with native IOS navigation you can find the implementation [here](https://github.com/alexzhirkevich/compose-cupertino/blob/master/cupertino-decompose/src/iosMain/kotlin/io/github/alexzhirkevich/cupertino/decompose/UIKitChildren.kt). I am planning to make something similar to cupertino-decompose with androidx.navigation that recently became multiplatform
