### ISSUE TITLE
Roll out release for Kotlin 2.0.0

### ISSUE THREAD

**Issue by blakelee** [alexzhirkevich/compose-cupertino#52]
Hey, I just discovered this project and saw that there were a few commits to support Kotlin 2.0.0. I was wondering if there are other bugs fixes that need to be done before a release or if we should be expecting a release pretty soon? I just saw this library but I'm on Kotlin 2.0.0 for my project and can't use it yet. Great job with the work you've done!

**Comment by alexzhirkevich** [comment]
How does Kotlin version stop you from using the library?

**Comment by begali** [comment]
@blakelee If you get missing resources error, delete build folder in your project. I am using kotlin 2.0.0 and compose multiplatform 1.6.10.

**Comment by blakelee** [comment]
It looked to be an issue with some code generation strangely enough. I reimported the library and now it seems to be working 🤷 

I'll reopen if I can reproduce it and see which iOS component it is.
