### ISSUE TITLE
How can you read the current color scheme or create a custom widget

### ISSUE THREAD

**Issue by garretyoder** [alexzhirkevich/compose-cupertino#59]
I see that you can use the base AdapativeWidget which provides you a Cupertino or material hook depending on which theme is set, but it looks like all of the color specs are implemented through `Adaption` and it's implementations - however these seem to be private and/or unusable. How does one go about getting the current colorScheme or creating a custom widget that matches the set colorScheme of the current theme?

 I suppose this is easy if the color scheme is static and you know it at compile time, but like in the example app for this repo I'd like to mix this with MaterialKolor, so the color palette can change based on user choice - and on material widgets a given color is not 1:1 with the inputted seed color.

**Comment by alexzhirkevich** [comment]
You can use CupertinoTheme.colorScheme just like for Material

**Comment by garretyoder** [comment]
This solves the problem, thanks. Maybe it would be useful to add a common theme object that pulls the colorspace from either theme where the colors line up? (primary -> primary, background -> surface, etc). I did something similar myself.

Closing issue.
