### ISSUE TITLE
CupertinoTheme is broken

### ISSUE THREAD

**Issue by schott12521** [alexzhirkevich/compose-cupertino#73]
I haven't spent anytime investigating it, but when using the example app, if you toggle between "Native" on the wheel picker, the theme switches between a transparent background and a solid white.

Bad - shouldn't be white
![image](https://github.com/user-attachments/assets/ee8ba4ee-80b5-4a0f-9b41-c8cc03fc01df)

Good - should be see through
![image](https://github.com/user-attachments/assets/67726c01-9844-4a6c-ab49-dc308ff318d7)

**Comment by alexzhirkevich** [comment]
see #1

**Comment by schott12521** [comment]
> see #1 

I mean from your own reply on that PR:

> Thanks but this readme is temporary and will completely change after release

The README has in fact completely changed, and there's no longer a reference to this configuration option anywhere in the documentation for this project (that I found -- correct me if I'm wrong).

Maybe instead of referencing 2 year PRs when users have questions like this, we can either:

- Update the documentation to make this behavior well known and expected
- Update the example usage to indicate that we are taken advantage of the ability to flip the color between white and translucent, and it is not a bug.

**Comment by alexzhirkevich** [comment]
wrong tag. see #13
